accounts/urls.py
from django.urls import path, include

from .views import LoginAjaxView


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('login_ajax/', LoginAjaxView.as_view(), name='login_ajax'),
]

department_of_energy/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', include('lighting_objects.urls')),
    path('accounts/', include('accounts.urls')),
]

lighting_objects/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.views.static import serve
from django.conf.urls import *

urlpatterns = [
                  path('export_data_to_excel', export_data_to_excel, name='export_data_to_excel'),

                  path('powerengineers/', PowerEngineersListView.as_view(), name='powerengineers'),

                  path('electricitymeter/', ElectricityMeterListView.as_view(), name='electricitymeter'),
                  path('electricitymeter/<int:pk>/', ElectricityMeterDetailView.as_view(),
                       name='electricitymeter_detail'),

                  path('area/', AreaListView.as_view(), name='area'),

                  path('government/<int:pk>/', LocalGovernmentDetailView.as_view(), name='government_detail'),

                  path('supplier/<int:pk>/', SupplierDetailView.as_view(), name='supplier_detail'),

                  path('name_detail/<int:pk>/', LightingObjectNameDetailView.as_view(), name='name_detail'),

                  path('contract_info_detail/<int:pk>/', LightingObjectContractInfoDetailView.as_view(),
                       name='contract_info_detail'),

                  path('attachmentpoint_detail/<int:pk>/', AttachmentPointDetailView.as_view(),
                       name='attachmentpoint_detail'),
                  path('power_grid_organization/', PowerGridOrganizationListView.as_view(),
                       name='power_grid_organization'),

                  path('details_modal/<int:pk>/', DetailsAjaxView.as_view(), name='details_modal'),

                  path('all_objects/', LightingObjectsListView.as_view(template_name='objects.html'), name='objects'),
                  path('all_objects/<int:pk>/', LightingObjectDetailView.as_view(template_name='object_detail.html'),
                       name='object_detail'),
                  path('', CarouselListView.as_view(template_name='home.html'), name='home'),
                  url(r'^Files/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

              ]

lighting_objects/models.py
from django.db import models
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField
from department_of_energy.settings import STATIC_ROOT
from django.core.files.storage import FileSystemStorage


class PowerGridOrganization(models.Model):
    """
    Класс для представления Сетевой организации к которой относятся поставщики электроэнергии
    """
    name = models.CharField(max_length=255, unique=True, verbose_name='Название организации', help_text='Название организации')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Сетевая организация'
        verbose_name_plural = 'Сетевые организации'

    def __str__(self):
        return self.name


class Supplier(models.Model):
    """
    Класс для представления поставщика электроэнергии
    """
    name = models.CharField(max_length=255, unique=True, verbose_name='Название организации', help_text='Название организации')
    phone_number = PhoneNumberField(blank=True, verbose_name='Телефон', help_text='Контактный телефон')
    second_phone_number = PhoneNumberField(blank=True, verbose_name='Второй телефон', help_text='Второй телефон')
    email = models.EmailField(blank=True, verbose_name='Электронная почта', help_text='Электронная почта')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Поставщик электроэнергии'
        verbose_name_plural = 'Поставщики электроэнергии'

    def __str__(self):
        if self.name:
            return self.name
        else:
            return 'Нет названия'


class Area(models.Model):
    """
    Класс для представления РУАД
    """
    name = models.CharField(max_length=255, unique=True, verbose_name='Название', help_text='Название РУАД (Можайский)')
    short_name = models.PositiveSmallIntegerField(verbose_name='Номер РУАД', help_text='Номер РУАД')

    class Meta:
        ordering = ('name',)
        verbose_name = 'РУАД'
        verbose_name_plural = 'РУАДы'

    def __str__(self):
        return self.name

    # TODO Может можно убрать вызов этого метода
    def get_power_engineers(self, obj):
        return obj.engineers.all


class DistrictRoadDepartment(models.Model):
    """
    Модель для представления районно дорожного отдела (РДО)
    """
    name = models.CharField(unique=True, max_length=255, verbose_name='Название', help_text='Название РДО (Домодедовское)')
    area = models.ForeignKey(Area, verbose_name='РУАД', on_delete=models.CASCADE, related_name='departments')

    class Meta:
        verbose_name = 'РДО'
        verbose_name_plural = 'РДО'

    def __str__(self):
        return self.name


class LocalGovernment(models.Model):
    """
    Модель для представления органа местного самоуправления (ОМС)
    """
    name = models.CharField(max_length=255, verbose_name='Название', help_text='Название ОМС (г.о. Домодедово)')
    department = models.ForeignKey(DistrictRoadDepartment, verbose_name='ОМС', on_delete=models.CASCADE, related_name='governments')

    class Meta:
        verbose_name = 'ОМС'
        verbose_name_plural = 'ОМС'

    def __str__(self):
        return self.name


class PowerEngineer(models.Model):
    """
    Модель для представления контактных данных энергетика
    """
    verbose_name = models.CharField(max_length=70, verbose_name='ФИО', help_text='ФИО')
    phone_number = PhoneNumberField(verbose_name='Телефон', blank=True)
    area = models.OneToOneField(Area, verbose_name='РУАД', null=True, on_delete=models.SET_NULL, related_name='engineers')

    class Meta:
        verbose_name = 'Энергетик'
        verbose_name_plural = 'Энергетики'

    def __str__(self):
        return self.verbose_name


class ElectricityMeterModel(models.Model):
    """
    Класс для представления Модели счетчика
    """
    name = models.CharField(unique=True, max_length=100, verbose_name='Модель счётчика', help_text='Модель счётчика (Меркурий 27)')
    life_time = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name='Сколько лет до поверки', help_text='Через сколько лет требуется поверка')  # Срок службы до следующей поверки

    class Meta:
        verbose_name = 'Модель счетчика'
        verbose_name_plural = 'Модели счетчиков'

    def __str__(self):
        return self.name

    def get_lifetime(self):
        if self.life_time is not None:
            return self.life_time
        else:
            return 0


class Coordinate(models.Model):
    """
    Класс для представления координат на карте
    """
    latitude = models.FloatField(verbose_name='Широта', help_text='Широта')  # Широта
    longitude = models.FloatField(verbose_name='Долгота', help_text='Долгота')  # Долгота

    class Meta:
        unique_together = ('latitude', 'longitude')
        verbose_name = 'Координаты'
        verbose_name_plural = 'Координаты'

    def __str__(self):
        return str(self.longitude) + "," + str(self.latitude)


class InstallationLocation(models.Model):
    """
    Класс для представления места установки
    """
    place = models.CharField(max_length=100, verbose_name='Место установки', help_text='Место установки')
    coordinate = models.ForeignKey(Coordinate, verbose_name='Координаты', blank=True, null=True, default=None,
                                   on_delete=models.SET_NULL)  # Координаты

    class Meta:
        verbose_name = 'Место установки'
        verbose_name_plural = 'Места установки'
        unique_together = ('place', 'coordinate')

    def __str__(self):
        return self.place


class LightingObjectContractInfo(models.Model):
    """
    Модель для представления идентификационных данных по контракту для объектов освещения
    """
    name = models.CharField(null=True, blank=True, max_length=255, verbose_name='Название по контракту', help_text='Название по контракту')  # Имя по контракту
    number = models.CharField(max_length=50, verbose_name='Номер контракта', help_text='Номер контракта')
    object_number = models.CharField(max_length=50, verbose_name='Номер объекта в контракте')

    class Meta:
        unique_together = ('name', 'number', 'object_number')
        verbose_name = 'Информация по контракту'
        verbose_name_plural = 'Информация по контракту'

    def __str__(self):
        if self.name:
            return self.name
        else:
            return 'Не внесено название из контракта'


class AttachmentPointOwner(models.Model):
    """
    Класс для представления объекта владельца точки присоединения
    """
    name = models.CharField(max_length=255, unique=True, verbose_name='Название организации', help_text='Название организации')
    phone_number = PhoneNumberField(blank=True, verbose_name='Телефон', help_text='Контактный телефон')
    second_phone_number = PhoneNumberField(blank=True, verbose_name='Второй телефон', help_text='Второй телефон')
    email = models.EmailField(blank=True, verbose_name='Электронная почта', help_text='Электронная почта')
    power_grid_organization = models.ForeignKey(PowerGridOrganization, blank=True, null=True, verbose_name='Сетевая организация',
                                                on_delete=models.CASCADE, related_name='owners')

    class Meta:
        verbose_name = 'Владелец точки присоединения'
        verbose_name_plural = 'Владелецы точек присоединения'

    def __str__(self):
        return self.name


class Employee(models.Model):
    """
    Класс для представления работника сетевой организации
    """
    position = models.CharField(max_length=40, verbose_name='Должность', help_text='Должность')
    name = models.CharField(max_length=50, verbose_name='ФИО', help_text='ФИО')
    phone_number = PhoneNumberField(blank=True, verbose_name='Телефон', help_text='Контактный телефон')
    # second_phone_number = PhoneNumberField(blank=True, verbose_name='Второй телефон', help_text='Второй телефон')
    email = models.EmailField(blank=True, verbose_name='Электронная почта', help_text='Электронная почта')
    attachmentpointowner = models.ForeignKey(AttachmentPointOwner, null=True, on_delete=models.SET_NULL, verbose_name='Сетевая организация',
                                 related_name='employees')

    class Meta:
        verbose_name = 'Сотрудник сетевой организации'
        verbose_name_plural = 'Сотрудники сетевой организации'

    def __str__(self):
        return self.name


class Substation(models.Model):
    """
    Класс представления трансформаторной подстанции
    """

    number = models.CharField(max_length=75, verbose_name='Номер ТП')  # Номер ТП
    power = models.FloatField(blank=True, null=True, verbose_name='Максимальная мощность')  # Максимальная мощность
    coordinates = models.ForeignKey(Coordinate, verbose_name='Координаты', on_delete=models.SET_NULL, blank=True,
                                    null=True, default=None)  # Координаты

    class Meta:
        unique_together = ('number', 'coordinates')
        verbose_name = 'Трансформаторная подстанция'
        verbose_name_plural = 'Трансформаторные подстанции'

    def __str__(self):
        return str(self.number)


class AttachmentPoint(models.Model):
    """
    Класс для представления объекта точки присоединения
    """

    name = models.CharField(max_length=255, verbose_name='Точка присоединения', help_text='ВЛ, КЛ, РУ... от ТП')
    power = models.FloatField(blank=True, null=True, verbose_name='Максимальная мощность')  # Максимальная мощность
    owner = models.ForeignKey(AttachmentPointOwner,
                              null=True, blank=True,
                              on_delete=models.SET_NULL,
                              verbose_name='Владелец точки присоединения',
                              related_name='attachment_points')  # Владелец точки присоединения
    coordinates = models.ForeignKey(Coordinate, verbose_name='Координаты', on_delete=models.SET_NULL, blank=True, null=True, default=None)  # Координаты

    class Meta:
        unique_together = ('name', 'coordinates')
        verbose_name = 'Точка присоединения'

lighting_objects/forms.py
from django import forms


class DetailForm(forms.ModelForm):
    pass

lighting_objects/templates/area.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<link href="{% static 'css/table.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/tree-view.css' %}" rel="stylesheet" type="text/css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.css" rel="stylesheet" type="text/css"/>

    {% if user.is_authenticated %}
    {% if area_list %}
    <h3>РУАД->РДО->ОМС</h3>

    <ol class="list-group list-group-numbered tree-nav">
        {% for area in area_list %}
        <li class="list-group-item d-flex justify-content-between align-items-start list-group-item-success ">
            <details class="tree-nav__item is-expandable ms-2 me-auto">
                <summary class="tree-nav__item-title">{{ area.name }}
                <span class="badge bg-primary rounded-pill">{{ area.departments.all.count }}</span>
                </summary>
                <div class="ms-2 me-auto">
                    <ol class="list-group list-group-numbered nested">
                        {% for department in area.departments.all %}
                        <li class="list-group-item d-flex justify-content-between align-items-start list-group-item-warning">
                            <details class="tree-nav__item is-expandable ms-2 me-auto">
                                <summary class="tree-nav__item-title">{{ department.name }}
                                <span class="badge bg-primary rounded-pill">{{ department.governments.all.count }}</span>
                                </summary>
                                <div class="ms-2 me-auto">
                                    <ol class="list-group list-group-numbered">
                                        {% for government in department.governments.all %}
                                        <li class="list-group-item d-flex justify-content-between align-items-start">
                                            <div class="ms-2 me-auto">
                                                <div class="fw-bold">{{ government.name }}
                                                </div>
                                            </div>
                                        </li>
                                        {% endfor %}
                                    </ol>
                                </div>
                            </details>
                        </li>
                        {% endfor %}
                    </ol>
                </div>
            </details>
        </li>

        {% endfor %}
    </ol>
    {% else %}
    <p>Нет данных</p>
    {% endif %}
    {% endif %}

{% endblock content %}

lighting_objects/templates/attachmentpoint_detail.html
{% extends 'base_detail.html' %}

{% block content %}

<title>Детальная информация по точке присоединения</title>

<div class="container">
    <div class="row">
        <div class="col-sm-6">Точка присоединения:</div>
        <div class="col-sm-6">{{ attachmentpoint.name }}</div>
    </div>
    <hr>
    <div class="row">
        <div class="col-sm-6">Владелец точки присоединения: </div>
        <div class="col-sm-6">
                    {% if attachmentpoint.owner %}
                        {{ attachmentpoint.owner }}
                    {% endif %}
        </div>
    </div>
    <hr>
    {% if attachmentpoint.meters.all %}
    <div class="row">
            <div class="col-sm-6">Счётчики: </div>
            {% for meter in attachmentpoint.meters.all %}
                <div class="col-sm">
                        {{ meter.number }}
                </div>
            {% endfor %}
    </div>
    <hr>
    {% endif %}

    <div class="row">
            <div class="col-sm-6">Координаты:</div>
            <div class="col-sm-6">
                {% if attachmentpoint.coordinates %}
                    <a href="https://yandex.ru/maps/?pt={{electricitymeter.coordinates}}&z=18&l=map" target="_blank">
                        {{ attachmentpoint.coordinates }}
                    </a>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock content %}

lighting_objects/templates/base.html
<!-- templates/base.html -->
{% load static %}
<html>
<head>
    <title>Управление Главного энергетика</title>

    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/cdn/select2.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/cdn/dataTables.bootstrap5.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/cdn/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body class="container">

<header>
    <nav class="navbar navbar-expand-md bg-color fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Управление Главного Энергетика</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Переключатель навигации">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                {% if user.is_authenticated %}

                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link active" aria-current="page" href="{% url 'objects' %}">Объекты освещения</a>
                    <a class="nav-item nav-link active" href="{% url 'electricitymeter' %}">СЭЭ</a>
                    <a class="nav-item nav-link active" href="{% url 'powerengineers' %}">Энергетики</a>
                    <a class="nav-item nav-link active" href="{% url 'area' %}">ОМС</a>
                    <a class="nav-item nav-link active" href="{% url 'power_grid_organization' %}">Сетевые организации</a>
                    {% if user.is_staff %}
                    <a class="nav-item nav-link active" href="{% url 'admin:index' %}" target="_blank">Администрирование</a>
                    {% endif %}

                </div>

                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{% url 'logout' %}?next=/">{{ user.username }}, Выйти</a>
                </div>
                {% else %}
                <div class="navbar-nav">
                    <a class="nav-item nav-link active authenticate-message">Вы не авторизованы необходимо -></a>
                    <a class="nav-item nav-link active" href="#" data-bs-toggle="modal"
                       data-bs-target="#login_ajax">Войти</a>
                </div>
                {% endif %}

            </div>
        </div>
    </nav>

</header>
<br>
<br>
<br>

<script src="{% static 'js/cdn/jquery-3.5.1.js' %}"></script>
{% block content %}
{% endblock content %}

{% include "registration/modal_login.html" %}
{% include "details_modal.html" %}


<script src="{% static 'js/cdn/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/cdn/dataTables.bootstrap5.min.js' %}"></script>
<script src="{% static 'js/cdn/bootstrap.bundle.min.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>
<!--Страницы с сортировкой таблиц-->
<script src="{% static 'js/table_sort.js' %}"></script>

</body>
</html>

lighting_objects/templates/base_detail.html
<!-- templates/base_detail.html -->
{% load static %}
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link href="{% static 'css/base_detail.css' %}" rel="stylesheet">
    <title>Детальная информация</title>
</head>
<body class="container">

{% block content %}
{% endblock content %}

<script src="{% static 'js/dataTables.bootstrap5.min.js' %}"></script>
<script src="{% static 'js/cdn/popper.min.js' %}"></script>

</body>
</html>

lighting_objects/templates/details_modal.html
<div class="modal fade" id="details_modal" data-bs-backdrop="static" data-bs-keyboard="true" tabindex="-1"
     aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Детальная информация:</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="#" method="GET" id="name-detail-form" >
                <div class="modal-body">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                </div>
            </form>
        </div>
    </div>
</div>

lighting_objects/templates/electricitymeter.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<link href="{% static 'css/cdn/select2.min.css' %}" rel="stylesheet">

    {% if user.is_authenticated %}
    {% if electricitymeter_list %}

    <h2>Счетчики электроэнергии</h2>
    <hr>
    <form method="get">

        <div class="row">

            <div class="col">
                <label>Статус:</label>
                <br>
                {{ filter.form.active }}
            </div>

            <div class="col">
                <label>Тип:</label>
                <br>
                {{ filter.form.type }}
            </div>

            <div class="col">
                <label>Модель:</label>
                <br>
                {{ filter.form.model }}
            </div>

            <div class="col">
                <label>Номер:</label>
                <br>
                {{ filter.form.number }}
            </div>

        </div>

        <div class="row">
            <div class="col">
                <label>ЛНО:</label>
                {{ filter.form.lighting_object__contract_info__name }}
            </div>
        </div>
        <br>
    <button class="btn btn-primary" type="submit" >Отфильтровать</button>
    </form>
    <hr>
    <br>
    <table id="table_sort" class="table table-striped table-hover table-bordered" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th></th>
            <th>Номер счётчика</th>
            <th>Дата поверки</th>
            <th>Срок эксплуатации</th>
            <th>Тип</th>
            <th>Модель</th>
            <th>Коэффициенты трансформации</th>
            <th>Координаты</th>
            <th>Пломбы</th>
            <th>Место установки</th>
            <th>Объект освещения</th>
            <th>Активный</th>
        </tr>
        </thead>
        <tbody>
        {% for electricitymeter in filter.qs %}
        <tr>
            <td> {{ forloop.counter }} </td>
            {% if electricitymeter.number %}
            <td>{{ electricitymeter.number }}</td>
            {% else %}
            <td>Без номера</td>
            {% endif %}
            <td>
                {% if electricitymeter.check_date %}
                    {{ electricitymeter.check_date }}
                {% endif %}
            </td>
            <td>
                {% if electricitymeter.get_lifetime %}
                    {{ electricitymeter.get_lifetime }}
                {% endif %}
            </td>
            <td>
                {% if electricitymeter.type %}
                    {{ electricitymeter.type }}
                {% endif %}
            </td>

            <td>
                {% if electricitymeter.model %}
                    {{ electricitymeter.model }}
                {% endif %}
            </td>

            <td>
                {% if electricitymeter.transformation_ratios %}
                    {{ electricitymeter.transformation_ratios }}
                {% endif %}
            </td>
            <td>
                {% if electricitymeter.coordinates %}
                    <a href="https://yandex.ru/maps/?pt={{electricitymeter.coordinates}}&z=18&l=map" target="_blank">
                        {{ electricitymeter.coordinates }}
                    </a>
                {% endif %}
            </td>
            <td>
                {% if electricitymeter.seals %}
                    {{ electricitymeter.seals }}
                {% endif %}
            </td>
            <td>
                {% if electricitymeter.installation_location %}
                    {{ electricitymeter.installation_location }}
                {% endif %}
            </td>
            <td style="width:30px">
                {% if electricitymeter.lighting_object %}
                    <a href="{% url 'object_detail' electricitymeter.lighting_object.id %}" target="_blank">
                        {{ electricitymeter.lighting_object.contract_info.name }}
                    </a>
                {% endif %}
            </td>
            <td>{{ electricitymeter.get_active }}</td>
        </tr>
        {% endfor %}

        </tbody>
    </table>

    {% else %}
    <p>Нет данных</p>
    {% endif %}
    {% endif %}

<script src="{% static 'js/cdn/select2.min.js' %}" ></script>
<script src="{% static 'js/meters-select2.js' %}" ></script>

{% endblock content %}

lighting_objects/templates/government_detail.html
{% extends 'base_detail.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-6">Городской округ:</div>
        <div class="col-sm-6">{{ localgovernment.name }}</div>
    </div>
    <hr>
    <div class="row">
        <div class="col-sm-6">РДО:</div>
        <div class="col-sm-6">{{ localgovernment.department.name }}</div>
    </div>
    <hr>
    <div class="row">
        <div class="col-sm-6">Главный энергетик:</div>
        <div class="col-sm-6">{{ localgovernment.department.area.engineers.verbose_name }}</div>
    </div>
    <hr>
    <div class="row">
        <div class="col-sm-6">Номер телефона:</div>
        <div class="col-sm-6">{{ localgovernment.department.area.engineers.phone_number }}</div>
    </div>

</div>

{% endblock content %}

lighting_objects/templates/name_detail.html
{% extends 'base_detail.html' %}

{% block content %}

<title>Детальная информация по названию объекта</title>

<div class="container">

    <div class="row">
      <div class="col-sm-6">Название на балансе:</div>
      <div class="col-sm-6">{{ lightingobjectname.name }}</div>
    </div>
    <hr>
    <div class="row">
      <div class="col-sm-6">Инвентарный номер:</div>
      <div class="col-sm-6">{{ lightingobjectname.inventory_number }}</div>
    </div>


</div>

{% endblock content %}

lighting_objects/templates/power_grid_organization.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<link href="{% static 'css/table.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/tree-view.css' %}" rel="stylesheet" type="text/css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.css" rel="stylesheet" type="text/css"/>

    {% if user.is_authenticated %}
    {% if powergridorganization_list %}
    <h3>Сетевые организации</h3>

    <ol class="list-group list-group-numbered tree-nav">
        {% for organization in powergridorganization_list %}
        <li class="list-group-item d-flex justify-content-between align-items-start list-group-item-success ">
            <details class="tree-nav__item is-expandable ms-2 me-auto">
                <summary class="tree-nav__item-title">{{ organization.name }}
                    {% if organization.owners.all %}
                        <span class="badge bg-primary rounded-pill">{{ organization.owners.all.count }}</span>
                    {% endif %}
                </summary>
                <div class="ms-2 me-auto">
                    <ol class="list-group list-group-numbered nested">
                        {% for owner in organization.owners.all %}
                        <li class="list-group-item d-flex justify-content-between align-items-start list-group-item-warning">
                            {% if owner.employees.all %}
                            <details class="tree-nav__item is-expandable ms-2 me-auto">
                                <summary class="tree-nav__item-title">{{ owner.name }}
                                    <span class="badge bg-primary rounded-pill">{{ owner.employees.all.count }}</span>
                                </summary>
                                <div class="ms-2 me-auto">
                                    <ol class="list-group list-group-numbered">
                                    {% if owner.employees.all %}
                                    <table class="list-group-item table table-striped table-hover table-bordered" cellspacing="0" width="100%">
                                    <thead>
                                    <tr class="fw-bold">
                                        <th>Должность</th>
                                        <th>ФИО</th>
                                        <th>Телефон</th>
                                        <th>Email</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for employee in owner.employees.all %}
                                    <tr>
                                        <td>{{ employee.position }}</td>
                                        <td>{{ employee.name }}</td>
                                        <td>{{ employee.phone_number }}</td>
                                        <td>{{ employee.email }}</td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                    </table>
                                    {% endif %}
                                </ol>
                                </div>
                            </details>
                            {% else %}
                            <details class="tree-nav__item ms-2 me-auto">
                                <summary class="tree-nav__item-title">{{ owner.name }}</summary>
                            </details>
                            {% endif %}
                        </li>
                        {% endfor %}
                    </ol>
                </div>
            </details>
        </li>

        {% endfor %}
    </ol>
    {% else %}
    <p>Нет данных</p>
    {% endif %}
    {% endif %}

{% endblock content %}